name: C/C++ CI macos

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:
    runs-on: macos-11

    steps:
    -   name: Install Qt
    uses: WillBrennan/yaqti
    with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake -makefile CaptureStream0.pro
    - name: make
      run: make
      
    - name: Make CaptureStream0 executable
      run: sudo chmod -R 755 ./CaptureStream0.app
  
    - uses: actions/upload-artifact@v3
      with:
        name: CaptureStream0
        path: ./

